Merged PR 133244: 0000: update main branch with products-demo code - starting point
# Short description

0000: update main branch with products-demo code

Related work items: #306200, #306201, #306717, #306811

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,7 +2,9 @@ trigger:
   batch: true
   branches:
     include:
+      - develop
       - beta
+      - dev
 
 pool:
   name: WebPlu
@@ -14,7 +16,7 @@ resources:
     - repository: templates
       name: SXP-DevOps/d3ops-pipelines-templates
       type: git
-      ref: "refs/tags/build/common-solution/steps/1.1.3"
+      ref: "refs/tags/build/common-solution/steps/1.1.7"
 
 variables:
   - group: SonarSecret
@@ -52,6 +54,33 @@ variables:
     value: "18"
 
 steps:
+  # Validate PullRequest title format (adjust the PATTERN regex based on your project needs)
+  - script: | 
+      pr_title="$(curl --silent -u azdo:$SYSTEM_ACCESSTOKEN \
+        $(System.CollectionUri)_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(System.PullRequest.PullRequestId)?api-version=5.1 \
+        | grep -Po '"title":.*?[^\\]",' | cut -d'"' -f4)"
+      echo "Extracted PR title: $pr_title"
+      echo "##vso[task.setvariable variable=PR_TITLE]$pr_title"
+    env:
+      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+    displayName: Extract pull request title
+    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
+
+  - script: |
+      # Define the regex pattern
+      PATTERN='^[0-9]+:[[:space:]].{1,100}$'
+
+      # Display the PR title
+      echo "PR Title: $PR_TITLE"
+
+      # Validate the PR title using regex
+      if [[ ! $PR_TITLE =~ $PATTERN ]]; then
+        echo "PR title does not match the required format (e.g., 306193: add new feature). Please update the title."
+        exit 1
+      fi
+    displayName: Validate PR Title
+    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))    
+
   # Create GitFinalVersion variable
   - template: build/common-solution/steps/set-version-universal.yml@templates
 
